### ISSUE TITLE
virgil doesn't work under JDK 11

### ISSUE THREAD

**Issue by Bost** [ztellman/virgil#30]
Everything is fine under `openjdk version "1.8.0_191"`, however under `openjdk version "11.0.1" 2018-10-16` I get:
```
Exception in thread "main" Syntax error compiling at (/tmp/form-init5179779871166635250.clj:1:73).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at virgil.decompile$parents.invokeStatic(decompile.clj:12)
	at virgil.decompile$parents.invoke(decompile.clj:12)
	at virgil.decompile$rank_order$parents__8541.invoke(decompile.clj:24)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$zipmap.invokeStatic(core.clj:3071)
	at clojure.core$zipmap.invoke(core.clj:3071)
	at virgil.decompile$rank_order.invokeStatic(decompile.clj:25)
	at virgil.decompile$rank_order.invoke(decompile.clj:18)
	at virgil.compile$compile_java.invokeStatic(compile.clj:124)
	at virgil.compile$compile_java.invoke(compile.clj:119)
	at virgil.compile$compile_all_java.invokeStatic(compile.clj:161)
	at virgil.compile$compile_all_java.invoke(compile.clj:149)
	at virgil$watch$recompile__8667.invoke(virgil.clj:44)
	at virgil$watch.invokeStatic(virgil.clj:61)
	at virgil$watch.doInvoke(virgil.clj:41)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval8680.invokeStatic(form-init5179779871166635250.clj:1)
	at user$eval8680.invoke(form-init5179779871166635250.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
```

**Comment by Bost** [comment]
What a speedy response! Thanx Zach! :)
