### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException - Index ... out of bounds for length  ...

### ISSUE THREAD

**Issue by clov0** [ztellman/virgil#33]
Hi I keep getting this error when I try to compile the project : 
```
recompiling all files in ["/home/ho0man/Projects/focus/Storm-Kepper/storm-virgil-failure/src/java"]
Index 28527 out of bounds for length 194
Exception in thread "main" Syntax error compiling at (/tmp/form-init7228090304527752464.clj:1:73).
        at clojure.lang.Compiler.load(Compiler.java:7647)
        at clojure.lang.Compiler.loadFile(Compiler.java:7573)
        at clojure.main$load_script.invokeStatic(main.clj:452)
        at clojure.main$init_opt.invokeStatic(main.clj:454)
        at clojure.main$init_opt.invoke(main.clj:454)
        at clojure.main$initialize.invokeStatic(main.clj:485)
        at clojure.main$null_opt.invokeStatic(main.clj:519)
        at clojure.main$null_opt.invoke(main.clj:516)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 28527 out of bounds for length 194
        at org.objectweb.asm.ClassReader.getSuperName(Unknown Source)
        at virgil.decompile$parents.invokeStatic(decompile.clj:15)
        at virgil.decompile$parents.invoke(decompile.clj:12)
        at virgil.decompile$rank_order$parents__740.invoke(decompile.clj:24)
        at clojure.core$map$fn__5851.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:709)
        at clojure.core$next__5371.invokeStatic(core.clj:64)
        at clojure.core$zipmap.invokeStatic(core.clj:3079)
        at clojure.core$zipmap.invoke(core.clj:3071)
        at virgil.decompile$rank_order.invokeStatic(decompile.clj:25)
        at virgil.decompile$rank_order.invoke(decompile.clj:18)
        at virgil.compile$compile_java.invokeStatic(compile.clj:124)
        at virgil.compile$compile_java.invoke(compile.clj:119)
        at virgil.compile$compile_all_java.invokeStatic(compile.clj:161)
        at virgil.compile$compile_all_java.invoke(compile.clj:149)
        at virgil$watch$recompile__866.invoke(virgil.clj:44)
        at virgil$watch.invokeStatic(virgil.clj:61)
        at virgil$watch.doInvoke(virgil.clj:41)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at user$eval879.invokeStatic(form-init7228090304527752464.clj:1)
        at user$eval879.invoke(form-init7228090304527752464.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7165)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        ... 12 more
Compilation failed: Subprocess failed (exit code: 1)

```
I have put the code in this public repo if anyone wants more info on this : https://github.com/clov0/storm-virgil-failure

**Comment by alexander-yakushev** [comment]
Slim chance, but do you still have the reproducer somewhere?
